baseURL = "https://sixfoisneuf.fr/"
languageCode = "en-us"
title = "SixFoisNeuf"
theme = "ezhil"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    style = "vs"
    tabWidth = 4

[params]
subtitle = "Systems administration, DFIR and malware analysis"
featherIconsCDN = true

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/simsor"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/simsor"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About me"
url = "/about"
weight = 2

[[menu.main]]
name = "RSS"
url = "/posts/index.xml"
weight = 3